source 'https://github.com/CocoaPods/Specs.git'

target 'PCJSONRPC-Test-iOS' do
  platform :ios, '5.0'
  pod "PCJSONRPC", :path => "../"
end

target 'PCJSONRPC-Test-OSX' do
  platform :osx, '10.7'
  pod "PCJSONRPC", :path => "../"
end
